# Generated by Django 3.2.6 on 2021-12-29 04:53

from django.db import migrations
import performance.models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', performance.models.UserManager()),
            ],
        ),
    ]
