# Generated by Django 3.2.6 on 2021-09-01 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_auto_20210901_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastPerformance',
            fields=[
                ('performance_id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('concentration', models.IntegerField()),
                ('eyecontact', models.IntegerField()),
                ('clarity', models.IntegerField()),
                ('understanding', models.IntegerField()),
                ('confidence', models.IntegerField()),
                ('performance_datetime', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performanceQuestion', to='performance.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userPastPerformance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
