# Generated by Django 3.2.6 on 2021-12-29 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
